services:
  frontend:
    image: ghcr.io/appuser/frontend:latest
    restart: always
    ports:
      - "8080:80"

  backend:
    image: ghcr.io/appuser/backend:latest
    restart: always
    env_file:
      - ../.env
    ports:
      - "8081:8080"
